import { ArrowRight } from "lucide-react";
import Link from "next/link";
import { ProductCard } from "@/components/product-card";
import type { Product } from "@/types/models";

// Mock data for demonstration
const mockProducts: Product[] = [
	{
		id: "1",
		title: 'MacBook Pro 13" M2 - Perfect Condition',
		description:
			"Barely used MacBook Pro with Apple M2 chip, includes original box and accessories. Perfect for students and professionals.",
		price: 4500,
		compareAtPrice: 5200,
		images: ["/silver-macbook-on-desk.png"],
		category: { id: "1", name: "Electronics", slug: "electronics" },
		condition: "like-new",
		quantity: 1,
		status: "active",
		sellerId: "1",
		seller: {
			id: "1",
			email: "seller@uni.edu",
			firstName: "John",
			lastName: "Doe",
			role: "seller",
			isEmailVerified: true,
			isPhoneVerified: false,
			kycStatus: "approved",
			createdAt: "",
			updatedAt: "",
		},
		likesCount: 24,
		isLiked: false,
		tags: ["laptop", "apple", "macbook"],
		createdAt: "",
		updatedAt: "",
	},
	{
		id: "2",
		title: "Wireless Earbuds - Sony WF-1000XM4",
		description:
			"Premium noise cancelling earbuds with excellent battery life. Perfect for studying or commuting.",
		price: 650,
		compareAtPrice: 850,
		images: ["/wireless-earbuds-sony.jpg"],
		category: { id: "1", name: "Electronics", slug: "electronics" },
		condition: "new",
		quantity: 3,
		status: "active",
		sellerId: "2",
		seller: {
			id: "2",
			email: "seller2@uni.edu",
			firstName: "Jane",
			lastName: "Smith",
			role: "seller",
			isEmailVerified: true,
			isPhoneVerified: false,
			kycStatus: "approved",
			createdAt: "",
			updatedAt: "",
		},
		likesCount: 45,
		isLiked: true,
		tags: ["earbuds", "sony", "wireless"],
		createdAt: "",
		updatedAt: "",
	},
	{
		id: "3",
		title: "Calculus Textbook - Stewart 8th Edition",
		description:
			"Essential textbook for math majors. Clean pages, minimal highlighting. Great condition.",
		price: 85,
		compareAtPrice: 120,
		images: ["/calculus-textbook.png"],
		category: { id: "2", name: "Books", slug: "books" },
		condition: "good",
		quantity: 1,
		status: "active",
		sellerId: "3",
		seller: {
			id: "3",
			email: "seller3@uni.edu",
			firstName: "Mike",
			lastName: "Johnson",
			role: "seller",
			isEmailVerified: true,
			isPhoneVerified: false,
			kycStatus: "approved",
			createdAt: "",
			updatedAt: "",
		},
		likesCount: 12,
		isLiked: false,
		tags: ["textbook", "math", "calculus"],
		createdAt: "",
		updatedAt: "",
	},
	{
		id: "4",
		title: "Vintage Denim Jacket - Levi's",
		description:
			"Classic style denim jacket, size M. Authentic Levi's with vintage wash.",
		price: 120,
		compareAtPrice: 180,
		images: ["/denim-jacket-vintage.jpg"],
		category: { id: "3", name: "Fashion", slug: "fashion" },
		condition: "good",
		quantity: 1,
		status: "active",
		sellerId: "4",
		seller: {
			id: "4",
			email: "seller4@uni.edu",
			firstName: "Sarah",
			lastName: "Lee",
			role: "seller",
			isEmailVerified: true,
			isPhoneVerified: false,
			kycStatus: "approved",
			createdAt: "",
			updatedAt: "",
		},
		likesCount: 18,
		isLiked: false,
		tags: ["jacket", "fashion", "vintage", "levis"],
		createdAt: "",
		updatedAt: "",
	},
	{
		id: "5",
		title: "RGB Mechanical Gaming Keyboard",
		description:
			"Cherry MX switches, customizable RGB lighting. Perfect for gaming and coding.",
		price: 280,
		compareAtPrice: 350,
		images: ["/rgb-mechanical-keyboard.jpg"],
		category: { id: "1", name: "Electronics", slug: "electronics" },
		condition: "like-new",
		quantity: 2,
		status: "active",
		sellerId: "5",
		seller: {
			id: "5",
			email: "seller5@uni.edu",
			firstName: "David",
			lastName: "Chen",
			role: "seller",
			isEmailVerified: true,
			isPhoneVerified: true,
			kycStatus: "approved",
			createdAt: "",
			updatedAt: "",
		},
		likesCount: 31,
		isLiked: true,
		tags: ["keyboard", "gaming", "mechanical", "rgb"],
		createdAt: "",
		updatedAt: "",
	},
	{
		id: "6",
		title: "Aluminum Laptop Stand - Ergonomic",
		description:
			"Sleek aluminum stand for better posture. Compatible with all laptop sizes.",
		price: 95,
		images: ["/aluminum-laptop-stand.jpg"],
		category: { id: "4", name: "Accessories", slug: "accessories" },
		condition: "new",
		quantity: 5,
		status: "active",
		sellerId: "6",
		seller: {
			id: "6",
			email: "seller6@uni.edu",
			firstName: "Emily",
			lastName: "Brown",
			role: "seller",
			isEmailVerified: true,
			isPhoneVerified: false,
			kycStatus: "approved",
			createdAt: "",
			updatedAt: "",
		},
		likesCount: 22,
		isLiked: false,
		tags: ["stand", "laptop", "ergonomic", "aluminum"],
		createdAt: "",
		updatedAt: "",
	},
	{
		id: "7",
		title: "LED Desk Lamp - Modern Design",
		description:
			"Adjustable brightness and color temperature. USB charging port included.",
		price: 145,
		compareAtPrice: 200,
		images: ["/led-desk-lamp-modern.jpg"],
		category: { id: "5", name: "Home & Living", slug: "home-living" },
		condition: "new",
		quantity: 4,
		status: "active",
		sellerId: "7",
		seller: {
			id: "7",
			email: "seller7@uni.edu",
			firstName: "Alex",
			lastName: "Martinez",
			role: "seller",
			isEmailVerified: true,
			isPhoneVerified: true,
			kycStatus: "approved",
			createdAt: "",
			updatedAt: "",
		},
		likesCount: 16,
		isLiked: false,
		tags: ["lamp", "led", "desk", "study"],
		createdAt: "",
		updatedAt: "",
	},
	{
		id: "8",
		title: "Insulated Water Bottle - 32oz",
		description:
			"Keeps drinks cold for 24 hours, hot for 12 hours. BPA-free stainless steel.",
		price: 75,
		compareAtPrice: 95,
		images: ["/insulated-water-bottle.jpg"],
		category: { id: "6", name: "Sports & Fitness", slug: "sports-fitness" },
		condition: "new",
		quantity: 8,
		status: "active",
		sellerId: "8",
		seller: {
			id: "8",
			email: "seller8@uni.edu",
			firstName: "Chris",
			lastName: "Taylor",
			role: "seller",
			isEmailVerified: true,
			isPhoneVerified: false,
			kycStatus: "approved",
			createdAt: "",
			updatedAt: "",
		},
		likesCount: 29,
		isLiked: true,
		tags: ["water bottle", "insulated", "sports", "fitness"],
		createdAt: "",
		updatedAt: "",
	},
	{
		id: "9",
		title: "Laptop Backpack - Water Resistant",
		description:
			"Premium backpack with USB charging port and multiple compartments. Fits 15-inch laptops.",
		price: 165,
		compareAtPrice: 220,
		images: ["/laptop-backpack-black.jpg"],
		category: { id: "4", name: "Accessories", slug: "accessories" },
		condition: "new",
		quantity: 6,
		status: "active",
		sellerId: "9",
		seller: {
			id: "9",
			email: "seller9@uni.edu",
			firstName: "Rachel",
			lastName: "Kim",
			role: "seller",
			isEmailVerified: true,
			isPhoneVerified: true,
			kycStatus: "approved",
			createdAt: "",
			updatedAt: "",
		},
		likesCount: 38,
		isLiked: false,
		tags: ["backpack", "laptop", "water-resistant", "usb"],
		createdAt: "",
		updatedAt: "",
	},
	{
		id: "10",
		title: "College Textbooks Bundle - Engineering",
		description:
			"Set of 5 essential engineering textbooks. Excellent condition with minimal wear.",
		price: 320,
		compareAtPrice: 450,
		images: ["/college-textbooks-on-shelf.jpg"],
		category: { id: "2", name: "Books", slug: "books" },
		condition: "good",
		quantity: 1,
		status: "active",
		sellerId: "10",
		seller: {
			id: "10",
			email: "seller10@uni.edu",
			firstName: "Tom",
			lastName: "Wilson",
			role: "seller",
			isEmailVerified: true,
			isPhoneVerified: false,
			kycStatus: "approved",
			createdAt: "",
			updatedAt: "",
		},
		likesCount: 14,
		isLiked: false,
		tags: ["textbooks", "engineering", "bundle", "college"],
		createdAt: "",
		updatedAt: "",
	},
	{
		id: "11",
		title: "Ergonomic Wireless Mouse",
		description:
			"Comfortable design for long study sessions. Silent clicks and adjustable DPI.",
		price: 125,
		compareAtPrice: 160,
		images: ["/ergonomic-wireless-mouse.jpg"],
		category: { id: "1", name: "Electronics", slug: "electronics" },
		condition: "new",
		quantity: 7,
		status: "active",
		sellerId: "11",
		seller: {
			id: "11",
			email: "seller11@uni.edu",
			firstName: "Lisa",
			lastName: "Anderson",
			role: "seller",
			isEmailVerified: true,
			isPhoneVerified: true,
			kycStatus: "approved",
			createdAt: "",
			updatedAt: "",
		},
		likesCount: 27,
		isLiked: true,
		tags: ["mouse", "wireless", "ergonomic", "computer"],
		createdAt: "",
		updatedAt: "",
	},
	{
		id: "12",
		title: "Power Bank - 20000mAh Fast Charging",
		description:
			"High capacity power bank with dual USB ports. Charges phones up to 5 times.",
		price: 110,
		compareAtPrice: 145,
		images: ["/power-bank-black.jpg"],
		category: { id: "1", name: "Electronics", slug: "electronics" },
		condition: "new",
		quantity: 10,
		status: "active",
		sellerId: "12",
		seller: {
			id: "12",
			email: "seller12@uni.edu",
			firstName: "Kevin",
			lastName: "Zhang",
			role: "seller",
			isEmailVerified: true,
			isPhoneVerified: false,
			kycStatus: "approved",
			createdAt: "",
			updatedAt: "",
		},
		likesCount: 42,
		isLiked: false,
		tags: ["power bank", "charging", "portable", "battery"],
		createdAt: "",
		updatedAt: "",
	},
	{
		id: "13",
		title: "Wooden Desk Organizer Set",
		description:
			"Elegant bamboo desk organizer with pen holder, phone stand, and drawer.",
		price: 85,
		images: ["/wooden-desk-organizer.png"],
		category: { id: "5", name: "Home & Living", slug: "home-living" },
		condition: "new",
		quantity: 12,
		status: "active",
		sellerId: "13",
		seller: {
			id: "13",
			email: "seller13@uni.edu",
			firstName: "Nina",
			lastName: "Patel",
			role: "seller",
			isEmailVerified: true,
			isPhoneVerified: true,
			kycStatus: "approved",
			createdAt: "",
			updatedAt: "",
		},
		likesCount: 19,
		isLiked: false,
		tags: ["organizer", "desk", "wooden", "bamboo"],
		createdAt: "",
		updatedAt: "",
	},
	{
		id: "14",
		title: "Study Notes & Notebooks Bundle",
		description:
			"Complete set of organized study notes and premium notebooks for various subjects.",
		price: 65,
		compareAtPrice: 90,
		images: ["/study-notes-notebook.jpg"],
		category: { id: "2", name: "Books", slug: "books" },
		condition: "good",
		quantity: 3,
		status: "active",
		sellerId: "14",
		seller: {
			id: "14",
			email: "seller14@uni.edu",
			firstName: "Omar",
			lastName: "Hassan",
			role: "seller",
			isEmailVerified: true,
			isPhoneVerified: false,
			kycStatus: "approved",
			createdAt: "",
			updatedAt: "",
		},
		likesCount: 11,
		isLiked: true,
		tags: ["notebooks", "study", "notes", "school"],
		createdAt: "",
		updatedAt: "",
	},
];
export function FeaturedProducts() {
	return (
		<section className="py-12 px-4 sm:px-6 lg:px-8">
			<div className="mx-auto max-w-360">
				<div className="flex items-center justify-between mb-6">
					<h2 className="text-2xl font-bold text-foreground">Featured Products</h2>
					<Link
						href="/products"
						className="flex items-center gap-1 text-sm font-medium text-primary hover:text-primary/20 transition-colors"
					>
						View All
						<ArrowRight className="h-4 w-4" />
					</Link>
				</div>

				<div className="grid grid-cols-2  sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
					{mockProducts.map((product) => (
						<ProductCard key={product.id} product={product} />
					))}
				</div>
			</div>
		</section>
	);
}
